const codeMirrorOptions = {
	lineNumbers: true,
	highlightActiveLineGutter: true,
	highlightSpecialChars: true,
	history: true,
	foldGutter: true,
	drawSelection: true,
	dropCursor: false,
	allowMultipleSelections: false,
	indentOnInput: true,
	syntaxHighlighting: true,
	bracketMatching: true,
	closeBrackets: true,
	autocompletion: true,
	rectangularSelection: true,
	highlightActiveLine: true,
	highlightSelectionMatches: true,
	closeBracketsKeymap: true,
	defaultKeymap: true,
	searchKeymap: false,
	historyKeymap: true,
	foldKeymap: true,
	completionKeymap: true,
	lintKeymap: true,
	tabSize: 2,
};

export default codeMirrorOptions;
