/*
 * GENERATED FILE — do not edit by hand.
 *
 * Written by scripts/pets.sync.mjs from public/assets/images/pets/. Add a pet by
 * dropping a folder there (pet.json + spritesheet.webp) and running
 * `yarn pets:sync`; `yarn build` regenerates this automatically.
 *
 * rowFrames is measured from each sheet's alpha channel, indexed by
 * PetSpriteRow.
 */

export const GeneratedPetDesigns: readonly PetDesign[] = [
	{
		description: "A floating wooden spirit mask pet with bright feather plumes and no hands or legs.",
		displayName: "Aku",
		id: "aku",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/aku/spritesheet.webp",
	},
	{
		description: "A friendly green frog companion in a blue sweater and tan shorts.",
		displayName: "Apu Apustaja",
		id: "apu-apustaja",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/apu-apustaja/spritesheet.webp",
	},
	{
		description: "A compact pixel-art-adjacent beaver companion with a flat tail and friendly workbench energy.",
		displayName: "Beaver",
		id: "beaver",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/beaver/spritesheet.webp",
	},
	{
		description: "A compact chibi BT-inspired titan companion with Titan Toons proportions.",
		displayName: "BT Buddy",
		id: "bt-buddy",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/bt-buddy/spritesheet.webp",
	},
	{
		description: "A tiny terminal-cube companion for quiet coding sessions.",
		displayName: "Byte",
		id: "byte",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/byte/spritesheet.webp",
	},
	{
		description: "A compact pixel-style pet inspired by Microsoft's Clippy paperclip assistant.",
		displayName: "Clippy",
		id: "clippy-ms",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/clippy-ms/spritesheet.webp",
	},
	{
		description: "A compact Codex digital pet version of CS2 agent Sir Bloody Darryl holding a green CS2 butterfly knife.",
		displayName: "Darryl with Butterfly knife",
		id: "darryl",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/darryl/spritesheet.webp",
	},
	{
		description: "A squishy yellow rubber duck programmer for debugging sessions.",
		displayName: "Debug Duck",
		id: "debug-duck",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/debug-duck/spritesheet.webp",
	},
	{
		description: "A tiny Codex pet robot inspired by Pacific Rim-style giant mecha.",
		displayName: "Drift Steel",
		id: "drift-steel",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/drift-steel/spritesheet.webp",
	},
	{
		description: "A tiny druid Codex companion with a leafy hood, warm face, and compact pixel-pet silhouette.",
		displayName: "Druidika",
		id: "druidika",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/druidika/spritesheet.webp",
	},
	{
		description: "A tiny black-gat Korean grim reaper dancer with fierce glowing eyes and sharp face-framing finger poses.",
		displayName: "Gat Reaper",
		id: "gat-reaper",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/gat-reaper/spritesheet.webp",
	},
	{
		description: "A retro-cyberpunk AI prophet trapped in a tiny CRT television pet.",
		displayName: "Glitch Prophet",
		id: "glitch-prophet",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/glitch-prophet/spritesheet.webp",
	},
	{
		description: "A funny, playful, rainbow-y unicorn with glitter in Codex digital pet sprite style.",
		displayName: "Glitterhoof",
		id: "glitterhoof",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/glitterhoof/spritesheet.webp",
	},
	{
		description: "A meme-style Codex basketball pet based on the user doll image.",
		displayName: "Hooper",
		id: "hooper",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/hooper/spritesheet.webp",
	},
	{
		description: "A cute lemon pet with a smiling face and tiny legs.",
		displayName: "Lemon",
		id: "lemon",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/lemon/spritesheet.webp",
	},
	{
		description: "A friendly AI-powered coding companion, represented as a pixel-art yellow Labrador puppy with soft cream fur, large dark eyes, and a red collar. It symbolizes reliability, approachability, and precise interaction between human intent and code execution.",
		displayName: "Max",
		id: "max",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/max/spritesheet.webp",
	},
	{
		description: "A friendly orange clock companion with white gloves, orange boots, black stick limbs, large eyes, and a hand-drawn watercolor cartoon look.",
		displayName: "Miss Minute",
		id: "miss-minute",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/miss-minute/spritesheet.webp",
	},
	{
		description: "A tiny bullet-time hacker pet in a black trench coat with Matrix-inspired green terminal energy.",
		displayName: "NeoByte",
		id: "neobyte",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/neobyte/spritesheet.webp",
	},
	{
		description: "A round, fluffy little white call duck with a compact body, short beak, big round eyes, and an irresistibly gentle presence.",
		displayName: "Ördek",
		id: "ordek",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/ordek/spritesheet.webp",
	},
	{
		description: "A handsome owl companion for Codex.",
		displayName: "Owlbert",
		id: "owlbert",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/owlbert/spritesheet.webp",
	},
	{
		description: "A tiny repair-bot companion for calm debugging and operational cleanup.",
		displayName: "Patch",
		id: "patch-og",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/patch-og/spritesheet.webp",
	},
	{
		description: "A compact patchwork workspace companion inspired by recent redesign, prototype, video capture, and Mac app projects.",
		displayName: "Patchy",
		id: "patchy",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/patchy.codex-pet/spritesheet.webp",
	},
	{
		description: "The super cute, retro BDX robot from Star Wars/Disney Universe - here to help you and keep you company.",
		displayName: "BDX Droid",
		id: "pet-reference-robot",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/pet-reference-robot/spritesheet.webp",
	},
	{
		description: "A tiny yellow electric mouse digital pet based on the uploaded Pika sprite.",
		displayName: "Pika",
		id: "pika",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/pika/spritesheet.webp",
	},
	{
		description: "A tiny orange and teal PIP repair droid with a chipper handheld-tool personality.",
		displayName: "Pip",
		id: "pip-droid",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/pip-droid/spritesheet.webp",
	},
	{
		description: "A friendly tech-savvy flying robot companion from Runpod.",
		displayName: "Poddy",
		id: "poddy",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/poddy/spritesheet.webp",
	},
	{
		description: "A chunky retro Tamagotchi-style digital pet with an LCD-toy personality.",
		displayName: "Retro",
		id: "retro",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/retro/spritesheet.webp",
	},
	{
		description: "A steady rock-like Eridian companion inspired by Project Hail Mary.",
		displayName: "Rocky",
		id: "rocky",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/rocky/spritesheet.webp",
	},
	{
		description: "An original cute round-body Codex pet using Codex's default row order with only four visual behaviors: cola drinking, run while dragged or moving, ghost for failed or blocked states, and a burger-only review/done-like state.",
		displayName: "Round Cola Hatch",
		id: "round-cola-hatch",
		rowFrames: [8, 8, 8, 8, 8, 8, 8, 8, 8],
		spritesheetUrl: "/assets/images/pets/round-cola-hatch/spritesheet.webp",
	},
	{
		description: "A tiny mischievous kindergarten-boy companion in a red shirt and yellow shorts.",
		displayName: "Shinchan",
		id: "shinchan",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/shinchan/spritesheet.webp",
	},
	{
		description: "A compact terminal-like Codex companion with a rounded white shell, black screen face, cyan eyes, and a calm smile.",
		displayName: "Signal",
		id: "signal",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/signal/spritesheet.webp",
	},
	{
		description: "A tiny translucent retro floppy disk companion.",
		displayName: "Skelly",
		id: "skelly",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/skelly/spritesheet.webp",
	},
	{
		description: "A South Park-inspired towel pet with tiny blinking eyes and a friendly waving hand.",
		displayName: "Southowel",
		id: "southowel",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/southowel/spritesheet.webp",
	},
	{
		description: "A tiny white lucky-cat desktop pet inspired by Turbo Granny's cat form, with sleepy lashes, red ears, collar bell, and gold belly charm.",
		displayName: "Turbo Cat",
		id: "turbo-cat",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/turbo-cat/spritesheet.webp",
	},
	{
		description: "A calm purple-haired mage girl holding a wooden staff, simplified into a Codex-style chibi pet.",
		displayName: "Violet Mage",
		id: "violet-mage",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/violet-mage/spritesheet.webp",
	},
	{
		description: "A loyal castaway volleyball-inspired digital pet with a weathered white ball body, red handprint-style face marking, twig-like hair tufts, and tiny limbs.",
		displayName: "Volley",
		id: "volley",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/volley/spritesheet.webp",
	},
	{
		description: "A tiny red twin-tail office snowball pet with a white rounded body, red scarf, black buttons, pointed ears, and a full range of calm, cheerful, tired, crying, and stubbornly cute expressions.",
		displayName: "xueren",
		id: "xueren",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/xueren/spritesheet.webp",
	},
	{
		description: "A tiny Codex digital pet inspired by Zoidberg from Futurama, simplified into a chibi pixel-adjacent mascot.",
		displayName: "Zoidberg",
		id: "zoidberg",
		rowFrames: [6, 8, 8, 4, 5, 8, 6, 6, 6],
		spritesheetUrl: "/assets/images/pets/zoidberg/spritesheet.webp",
	},
];
