const enum SupportedLanguages {
	Markdown = "markdown",
	Bash = "bash",
	C = "c",
	Cpp = "cpp",
	CSS = "css",
	Dart = "dart",
	Go = "go",
	HTML = "html",
	Java = "java",
	JavaScript = "JavaScript",
	JSON = "json",
	Kotlin = "kotlin",
	PHP = "php",
	Python = "python",
	Ruby = "ruby",
	Rust = "rust",
	SQL = "sql",
	Swift = "swift",
	TypeScript = "TypeScript",
	YAML = "yaml",
}

export const languageAbbreviations: Record<string, string> = {
	[SupportedLanguages.Markdown]: "MD",
	[SupportedLanguages.Bash]: "SH",
	[SupportedLanguages.C]: "C",
	[SupportedLanguages.Cpp]: "C++",
	[SupportedLanguages.CSS]: "CSS",
	[SupportedLanguages.Dart]: "DAR",
	[SupportedLanguages.Go]: "GO",
	[SupportedLanguages.HTML]: "HTML",
	[SupportedLanguages.Java]: "JAV",
	[SupportedLanguages.JavaScript]: "JS",
	[SupportedLanguages.JSON]: "JSON",
	[SupportedLanguages.Kotlin]: "KT",
	[SupportedLanguages.PHP]: "PHP",
	[SupportedLanguages.Python]: "PY",
	[SupportedLanguages.Ruby]: "RB",
	[SupportedLanguages.Rust]: "RS",
	[SupportedLanguages.SQL]: "SQL",
	[SupportedLanguages.Swift]: "SWT",
	[SupportedLanguages.TypeScript]: "TS",
	[SupportedLanguages.YAML]: "YML",
};

export default SupportedLanguages;
